# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-20 15:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testManage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leveltype',
            name='prevLevel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='testManage.LevelType'),
        ),
    ]
