# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-31 14:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testManage', '0004_auto_20161028_1702'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='level',
            name='testObject',
        ),
        migrations.RemoveField(
            model_name='leveltype',
            name='testObject',
        ),
        migrations.AddField(
            model_name='testobject',
            name='testLevelTypes',
            field=models.ManyToManyField(null=True, to='testManage.LevelType'),
        ),
        migrations.AddField(
            model_name='testobject',
            name='testLevels',
            field=models.ManyToManyField(null=True, to='testManage.Level'),
        ),
    ]
