# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-09 14:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testManage', '0007_leveltype_testobjects'),
    ]

    operations = [
        migrations.AddField(
            model_name='level',
            name='testObjects',
            field=models.ManyToManyField(to='testManage.TestObject'),
        ),
    ]
