# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-09 15:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testManage', '0008_level_testobjects'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='level',
            name='testObjects',
        ),
        migrations.RemoveField(
            model_name='leveltype',
            name='testObjects',
        ),
        migrations.AlterField(
            model_name='testobject',
            name='testLevels',
            field=models.ManyToManyField(related_name='testObjects', to='testManage.Level'),
        ),
    ]
