# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-10 22:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testManage', '0009_auto_20161109_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='level',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='testManage.Level'),
        ),
    ]
